
package org.apache.axis2.jaxws.rpclit.stringarray.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import org.test.rpclit.stringarray.StringArray;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://sei.stringarray.rpclit.jaxws.axis2.apache.org")
@SOAPBinding(style = Style.RPC)
public interface Echo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String echoString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.test.rpclit.stringarray.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public StringArray echoStringArray(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0);

}
