<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="http://nonanonymous.complextype.test.org" 
      xmlns:tns="http://nonanonymous.complextype.test.org"
      xmlns="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"  jaxb:version="2.0"
      xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	 

   <types>
      <xsd:schema targetNamespace="http://nonanonymous.complextype.test.org"
         xmlns:ts="http://nonanonymous.complextype.test.org/xsd"
         xmlns="http://www.w3.org/2001/XMLSchema"
         elementFormDefault="qualified">

         <complexType name="echoMessage">
            <sequence>
               <element name="request" type="xsd:string"/>
            </sequence>
         </complexType>

         <complexType name="echoMessageResponse">
            <sequence>
               <element name="response" type="xsd:string"/>
            </sequence>
         </complexType>

         <element name="echoMessage" type="tns:echoMessage"/>
         <element name="echoMessageResponse" type="tns:echoMessageResponse"/>
         
<!-- Using schema binding to change the package name for jaxb art effects -->		
		<jaxb:schemaBindings>
			<jaxb:package name = "org.test.echomessage" />
		</jaxb:schemaBindings>
      </xsd:schema>
   </types>

   <message name="echoMessage">
      <part name="message" element="tns:echoMessage"/>
   </message>

   <message name="echoMessageResponse">
      <part name="result" element="tns:echoMessageResponse"/>
   </message>

   <portType name="EchoMessagePortType">
      <operation name="echoMessage">
         <input message="tns:echoMessage" />
         <output message="tns:echoMessageResponse" />
      </operation>
   </portType>

   <binding name="EchoMessageBinding" type="tns:EchoMessagePortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="echoMessage">
         <soap:operation soapAction=""/>
         <input>
            <soap:body use="literal"/>
         </input>

         <output>
            <soap:body use="literal"/>
         </output>
      </operation>
   </binding>

   <service name="EchoMessageService">
      <port binding="tns:EchoMessageBinding" name="EchoMessagePort">
         <soap:address location="http://localhost:8080/EchoMessageService/EchoMessageService"/>
      </port>

   </service>

</definitions>
