
package org.apache.axis2.jaxws.sample.addnumbershandler;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AddNumbersHandlerService", targetNamespace = "http://org/test/addnumbershandler", wsdlLocation = "AddNumbersHandler1.wsdl")
public class AddNumbersHandlerService
    extends Service
{

    private final static URL ADDNUMBERSSERVICE_WSDL_LOCATION;
    private static String wsdlLocation="/test/org/apache/axis2/jaxws/sample/addnumbershandler/META-INF/AddNumbersHandler.wsdl";
    static {
        URL url = null;
        try {
        	try{
	        	String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
	        	wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
        	}catch(Exception e){
        		e.printStackTrace();
        	}
        	File file = new File(wsdlLocation);
        	url = file.toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ADDNUMBERSSERVICE_WSDL_LOCATION = url;
    }

    public AddNumbersHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNumbersHandlerService() {
        super(ADDNUMBERSSERVICE_WSDL_LOCATION, new QName("http://org/test/addnumbershandler", "AddNumbersHandlerService"));
    }

    /**
     * 
     * @return
     *     returns AddNumbersHandlerPortType
     */
    @WebEndpoint(name = "AddNumbersHandlerPort")
    public AddNumbersHandlerPortType getAddNumbersHandlerPort() {
        return (AddNumbersHandlerPortType)super.getPort(new QName("http://org/test/addnumbershandler", "AddNumbersHandlerPort"), AddNumbersHandlerPortType.class);
    }

}
