
package org.apache.axis2.jaxws.proxy.doclitnonwrapped.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import org.test.proxy.doclitnonwrapped.Invoke;
import org.test.proxy.doclitnonwrapped.ReturnType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DocLitnonWrappedProxy", targetNamespace = "http://doclitnonwrapped.proxy.test.org")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface DocLitnonWrappedProxy {


    /**
     * 
     * @param allByMyself
     * @return
     *     returns org.test.proxy.doclitnonwrapped.ReturnType
     */
    @WebMethod(action = "http://doclitnonwrapped.proxy.test.org/invokeReturn")
    @WebResult(name = "ReturnType", targetNamespace = "http://doclitnonwrapped.proxy.test.org", partName = "allByMyself")
    public ReturnType invoke(
        @WebParam(name = "invoke", targetNamespace = "http://doclitnonwrapped.proxy.test.org", partName = "allByMyself")
        Invoke allByMyself);

}
