
package org.apache.axis2.jaxws.proxy.rpclit.sei;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "RPCLitService", targetNamespace = "http://org/apache/axis2/jaxws/proxy/rpclit", wsdlLocation = "RPCLit.wsdl")
public class RPCLitService
    extends Service
{

    private final static URL RPCLITSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/rpctest/sample/RPCLit.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RPCLITSERVICE_WSDL_LOCATION = url;
    }

    public RPCLitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RPCLitService() {
        super(RPCLITSERVICE_WSDL_LOCATION, new QName("http://org/apache/axis2/jaxws/proxy/rpclit", "RPCLitService"));
    }

    /**
     * 
     * @return
     *     returns RPCLit
     */
    @WebEndpoint(name = "RPCLit")
    public RPCLit getRPCLit() {
        return (RPCLit)super.getPort(new QName("http://org/apache/axis2/jaxws/proxy/rpclit", "RPCLit"), RPCLit.class);
    }

}
