package org.apache.axis2.jaxws.proxy.rpclitswa.sei;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "RPCLitSWAService", targetNamespace = "http://org/apache/axis2/jaxws/proxy/rpclitswa", wsdlLocation = "rpclitswa.wsdl")
public class RPCLitSWAService
    extends Service
{

    private final static URL RPCLITSWAERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/defects/rpclitswa.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RPCLITSWAERVICE_WSDL_LOCATION = url;
    }

    public RPCLitSWAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RPCLitSWAService() {
        super(RPCLITSWAERVICE_WSDL_LOCATION, new QName("http://org/apache/axis2/jaxws/proxy/rpclitswa", "RPCLitSWAService"));
    }

    /**
     * 
     * @return
     *     returns RPCLitSWA
     */
    @WebEndpoint(name = "RPCLitSWA")
    public RPCLitSWA getRPCLitSWA() {
        return (RPCLitSWA)super.getPort(new QName("http://org/apache/axis2/jaxws/proxy/rpclitswa", "RPCLitSWA"), RPCLitSWA.class);
    }

}
