
package org.apache.axis2.jaxws.proxy.gorilla_dlw.sei;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GorillaService", targetNamespace = "http://org/apache/axis2/jaxws/proxy/gorilla_dlw", wsdlLocation = "gorilla_dlw.wsdl")
public class GorillaService
    extends Service
{

    private final static URL GORILLASERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/compwsdl/gorilla_dlw.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GORILLASERVICE_WSDL_LOCATION = url;
    }

    public GorillaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GorillaService() {
        super(GORILLASERVICE_WSDL_LOCATION, new QName("http://org/apache/axis2/jaxws/proxy/gorilla_dlw", "GorillaService"));
    }

    /**
     * 
     * @return
     *     returns GorillaInterface
     */
    @WebEndpoint(name = "GorillaPort")
    public GorillaInterface getGorillaPort() {
        return (GorillaInterface)super.getPort(new QName("http://org/apache/axis2/jaxws/proxy/gorilla_dlw", "GorillaPort"), GorillaInterface.class);
    }

}
