
package org.apache.axis2.jaxws.sample.addnumbers;

import javax.xml.ws.WebFault;

import org.test.addnumbers.AddNumbersFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(faultBean="", name = "AddNumbersFault", targetNamespace = "http://duke/org")
public class AddNumbersFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AddNumbersFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AddNumbersFault_Exception(String message, AddNumbersFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public AddNumbersFault_Exception(String message, AddNumbersFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: duke.org.AddNumbersFault
     */
    public AddNumbersFault getFaultInfo() {
        return faultInfo;
    }

}
