
package org.apache.axis2.jaxws.proxy.rpclitswa.sei;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RPCLitSWA", targetNamespace = "http://org/apache/axis2/jaxws/proxy/rpclitswa", wsdlLocation = "RPCLitSWA.wsdl")
@SOAPBinding(style = Style.RPC)
public interface RPCLitSWA {


    /**
     * 
     * @param request
     * @param dummyAttachmentINOUT
     * @param dummyAttachmentOUT
     * @param response
     * @param dummyAttachmentIN
     */
    @WebMethod
    public void echo(
        @WebParam(name = "request", partName = "request")
        String request,
        @WebParam(name = "dummyAttachmentIN", partName = "dummyAttachmentIN")
        String dummyAttachmentIN,
        @WebParam(name = "dummyAttachmentINOUT", mode = Mode.INOUT, partName = "dummyAttachmentINOUT")
        Holder<DataHandler> dummyAttachmentINOUT,
        @WebParam(name = "response", mode = Mode.OUT, partName = "response")
        Holder<String> response,
        @WebParam(name = "dummyAttachmentOUT", mode = Mode.OUT, partName = "dummyAttachmentOUT")
        Holder<String> dummyAttachmentOUT);

}
