//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package org.apache.axis2.jaxws.sample.asyncdoclit.server;

import javax.xml.ws.WebFault;
import org.test.asyncdoclit.ThrowExceptionFaultBean;

@WebFault(name = "throwExceptionFaultBean", targetNamespace = "http://org/test/asyncdoclit")
public class ThrowExceptionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ThrowExceptionFaultBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ThrowExceptionFault(String message, ThrowExceptionFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ThrowExceptionFault(String message, ThrowExceptionFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.test.asyncdoclit.ThrowExceptionFaultBean
     */
    public ThrowExceptionFaultBean getFaultInfo() {
        return faultInfo;
    }

}
