
package org.apache.axis2.jaxws.anytype.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AnyTypeMessagePortType", targetNamespace = "http://anytype.test.org")
public interface AnyTypeMessagePortType {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://anytype.test.org")
    @RequestWrapper(localName = "echoMessage", targetNamespace = "http://anytype.test.org", className = "org.test.anytype.EchoMessage")
    @ResponseWrapper(localName = "echoMessageResponse", targetNamespace = "http://anytype.test.org", className = "org.test.anytype.EchoMessageResponse")
    public Object echoMessage(
        @WebParam(name = "request", targetNamespace = "http://anytype.test.org")
        Object request);

}
