<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://doclitbaremin.sample.test.org"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DoclitBareMin"
	targetNamespace="http://doclitbaremin.sample.test.org">
	
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://doclitbaremin.sample.test.org"
			xmlns:tns="http://doclitbaremin.sample.test.org"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		
		<xsd:element name="String" type="xsd:string" />

		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="SingleParam">
		<wsdl:part name="allByMyself" element="tns:String" />
	</wsdl:message>

	<wsdl:portType name="DocLitBareMinPortType">
		
		<wsdl:operation name="echo">
			<wsdl:input message="tns:SingleParam" />
			<wsdl:output message="tns:SingleParam" />
		</wsdl:operation>
			
	</wsdl:portType>
	
	<wsdl:binding name="DocLitBareMin" type="tns:DocLitBareMinPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		
		<wsdl:operation name="echo">
			<wsdl:input>
				<soap:body use="literal"  />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"  />
			</wsdl:output>
		</wsdl:operation>	
		
	
	</wsdl:binding>
	
	<wsdl:service name="BareDocLitMinService">
		<wsdl:port binding="tns:DocLitBareMin" name="BareDocLitMinPort">
			<soap:address location="http://localhost:8080/axis2/services/BareDocLitMinService" />
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>
