
package org.apache.axis2.jaxws.anytype.sei;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AnyTypeMessageService", targetNamespace = "http://anytype.test.org", wsdlLocation = "AnyType.wsdl")
public class AnyTypeMessageService
    extends Service
{

    private final static URL ANYTYPEMESSAGESERVICE_WSDL_LOCATION;

    private static String wsdlLocation="/test/org/apache/axis2/jaxws/anytype/META-INF/AnyType.wsdl";
    static {
        URL url = null;
        try {
        	try{
	        	String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
	        	wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
        	}catch(Exception e){
        		e.printStackTrace();
        	}
        	File file = new File(wsdlLocation);
        	url = file.toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ANYTYPEMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public AnyTypeMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnyTypeMessageService() {
        super(ANYTYPEMESSAGESERVICE_WSDL_LOCATION, new QName("http://anytype.test.org", "AnyTypeMessageService"));
    }

    /**
     * 
     * @return
     *     returns AnyTypeMessagePortType
     */
    @WebEndpoint(name = "AnyTypePort")
    public AnyTypeMessagePortType getAnyTypePort() {
        return (AnyTypeMessagePortType)super.getPort(new QName("http://anytype.test.org", "AnyTypePort"), AnyTypeMessagePortType.class);
    }

}
