
package org.apache.axis2.jaxws.nonanonymous.complextype.sei;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EchoMessageService", targetNamespace = "http://nonanonymous.complextype.test.org", wsdlLocation = "EchoMessage.wsdl")
public class EchoMessageService
    extends Service
{

    private final static URL ECHOMESSAGESERVICE_WSDL_LOCATION;

    private static String wsdlLocation="/test/org/apache/axis2/jaxws/nonanonymous/complextype/META-INF/EchoMessage.wsdl";
    static {
        URL url = null;
        try {
        	try{
	        	String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
	        	wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
        	}catch(Exception e){
        		e.printStackTrace();
        	}
        	File file = new File(wsdlLocation);
        	url = file.toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ECHOMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public EchoMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoMessageService() {
        super(ECHOMESSAGESERVICE_WSDL_LOCATION, new QName("http://nonanonymous.complextype.test.org", "EchoMessageService"));
    }

    /**
     * 
     * @return
     *     returns EchoMessagePortType
     */
    @WebEndpoint(name = "EchoMessagePort")
    public EchoMessagePortType getEchoMessagePort() {
        return (EchoMessagePortType)super.getPort(new QName("http://nonanonymous.complextype.test.org", "EchoMessagePort"), EchoMessagePortType.class);
    }

}
