
package org.apache.axis2.jaxws.nonanonymous.complextype.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EchoMessagePortType", targetNamespace = "http://nonanonymous.complextype.test.org")
public interface EchoMessagePortType {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://nonanonymous.complextype.test.org")
    @RequestWrapper(localName = "echoMessage", targetNamespace = "http://nonanonymous.complextype.test.org", className = "org.test.complextype.nonanonymous.EchoMessage")
    @ResponseWrapper(localName = "echoMessageResponse", targetNamespace = "http://nonanonymous.complextype.test.org", className = "org.test.complextype.nonanonymous.EchoMessageResponse")
    public String echoMessage(
        @WebParam(name = "request", targetNamespace = "http://nonanonymous.complextype.test.org")
        String request);

}
