
package org.apache.axis2.jaxws.stringlist.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlList;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StringListPortType", targetNamespace = "http://org/test/StringList")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface StringListPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.String[]
     */
    @XmlList
    @WebMethod(operationName = "StringList")
    @WebResult(name = "StringListResponse", targetNamespace = "http://org/test/StringList", partName = "result")
    public String[] stringList(
        @XmlList
        @WebParam(name = "StringList", targetNamespace = "http://org/test/StringList", partName = "parameters")
        String[] parameters);

}
