
package org.apache.axis2.jaxws.proxy.gorilla_dlw.sei;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "assertFault", targetNamespace = "http://org/apache/axis2/jaxws/proxy/gorilla_dlw/data")
public class AssertFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.apache.axis2.jaxws.proxy.gorilla_dlw.data.AssertFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AssertFault(String message, org.apache.axis2.jaxws.proxy.gorilla_dlw.data.AssertFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param message
     * @param faultInfo
     */
    public AssertFault(String message, org.apache.axis2.jaxws.proxy.gorilla_dlw.data.AssertFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.apache.axis2.jaxws.proxy.gorilla_dlw.data.AssertFault
     */
    public org.apache.axis2.jaxws.proxy.gorilla_dlw.data.AssertFault getFaultInfo() {
        return faultInfo;
    }

}
