
package org.apache.axis2.jaxws.sample.wsgen;

import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
import javax.jws.WebService;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSGenInterface", targetNamespace = "http://wsgen.sample.jaxws.axis2.apache.org")
public interface WSGenInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:EchoString")
    //@WebResult(targetNamespace = "")
    //@RequestWrapper(localName = "echoString", targetNamespace = "http://wsgen.sample.jaxws.axis2.apache.org", className = "org.apache.axis2.jaxws.sample.wsgen.EchoString")
    //@ResponseWrapper(localName = "echoStringResponse", targetNamespace = "http://wsgen.sample.jaxws.axis2.apache.org", className = "org.apache.axis2.jaxws.sample.wsgen.EchoStringResponse")
    public String echoString(
        //@WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
