
package org.apache.axis2.jaxws.sample.addnumbershandler;

import javax.xml.ws.WebFault;

import org.test.addnumbershandler.AddNumbersHandlerFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(faultBean="", name = "AddNumbersHandlerFault", targetNamespace = "http://duke/org")
public class AddNumbersHandlerFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AddNumbersHandlerFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AddNumbersHandlerFault_Exception(String message, AddNumbersHandlerFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public AddNumbersHandlerFault_Exception(String message, AddNumbersHandlerFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: duke.org.AddNumbersHandlerFault
     */
    public AddNumbersHandlerFault getFaultInfo() {
        return faultInfo;
    }

}
