
package org.apache.axis2.jaxws.proxy.doclitnonwrapped.sei;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProxyDocLitUnwrappedService", targetNamespace = "http://doclitnonwrapped.proxy.test.org", wsdlLocation = "proxy_doclit_unwr.wsdl")
public class ProxyDocLitUnwrappedService
    extends Service
{

    private final static URL PROXYDOCLITUNWRAPPEDSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/temp/proxy_doclit_unwr.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PROXYDOCLITUNWRAPPEDSERVICE_WSDL_LOCATION = url;
    }

    public ProxyDocLitUnwrappedService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyDocLitUnwrappedService() {
        super(PROXYDOCLITUNWRAPPEDSERVICE_WSDL_LOCATION, new QName("http://doclitnonwrapped.proxy.test.org", "ProxyDocLitUnwrappedService"));
    }

    /**
     * 
     * @return
     *     returns DocLitnonWrappedProxy
     */
    @WebEndpoint(name = "ProxyDocLitnonWrappedPort")
    public DocLitnonWrappedProxy getProxyDocLitnonWrappedPort() {
        return (DocLitnonWrappedProxy)super.getPort(new QName("http://doclitnonwrapped.proxy.test.org", "ProxyDocLitnonWrappedPort"), DocLitnonWrappedProxy.class);
    }

}
