
package org.apache.axis2.jaxws.sample.wsgen.client;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import org.apache.axis2.jaxws.sample.wsgen.client.WSGenInterface;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WSGenService", targetNamespace = "http://wsgen.sample.jaxws.axis2.apache.org", wsdlLocation = "WSGenService.wsdl")
public class WSGenService
    extends Service
{

    private final static URL WSGENSERVICE_WSDL_LOCATION;
    private static String wsdlLocation="/test/org/apache/axis2/jaxws/sample/wsgen/META-INF/WSGenService.wsdl";
    
    static {
        URL url = null;
        try {
            try{
                String baseDir = new File(System.getProperty("basedir",".")).getCanonicalPath();
                wsdlLocation = new File(baseDir + wsdlLocation).getAbsolutePath();
            }catch(Exception e){
                e.printStackTrace();
            }
            File file = new File(wsdlLocation);
            url = file.toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSGENSERVICE_WSDL_LOCATION = url;
    }

    public WSGenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGenService() {
        super(WSGENSERVICE_WSDL_LOCATION, new QName("http://wsgen.sample.jaxws.axis2.apache.org", "WSGenService"));
    }

    /**
     * 
     * @return
     *     returns WSGenInterface
     */
    @WebEndpoint(name = "WSGenPort")
    public WSGenInterface getWSGenPort() {
        return (WSGenInterface)super.getPort(new QName("http://wsgen.sample.jaxws.axis2.apache.org", "WSGenPort"), WSGenInterface.class);
    }

}
