
package org.apache.axis2.jaxws.sample.faultsservice;

import javax.xml.ws.WebFault;

import org.test.polymorphicfaults.DerivedFault1;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "DerivedFault1", targetNamespace = "http://org/test/polymorphicfaults")
public class DerivedFault1_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DerivedFault1 faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DerivedFault1_Exception(String message, DerivedFault1 faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param message
     * @param faultInfo
     */
    public DerivedFault1_Exception(String message, DerivedFault1 faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.test.polymorphicfaults.DerivedFault1
     */
    public DerivedFault1 getFaultInfo() {
        return faultInfo;
    }

}
