
package org.apache.axis2.jaxws.sample.faultsservice;

import javax.xml.ws.WebFault;

import org.test.polymorphicfaults.DerivedFault2;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "DerivedFault2", targetNamespace = "http://org/test/polymorphicfaults")
public class DerivedFault2_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DerivedFault2 faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DerivedFault2_Exception(String message, DerivedFault2 faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param message
     * @param faultInfo
     */
    public DerivedFault2_Exception(String message, DerivedFault2 faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.test.polymorphicfaults.DerivedFault2
     */
    public DerivedFault2 getFaultInfo() {
        return faultInfo;
    }

}
