<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="http://anytype.test.org" 
      xmlns:tns="http://anytype.test.org"
      xmlns="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

   <types>
      <xsd:schema targetNamespace="http://anytype.test.org"
         xmlns:ts="http://anytype.test.org/xsd"
         xmlns="http://www.w3.org/2001/XMLSchema"
         elementFormDefault="qualified">

         <complexType name="echoMessage">
            <sequence>
               <element name="request" type="xsd:anyType"/>
            </sequence>
         </complexType>

         <complexType name="echoMessageResponse">
            <sequence>
               <element name="response" type="xsd:anyType"/>
            </sequence>
         </complexType>

         <element name="echoMessage" type="tns:echoMessage"/>
         <element name="echoMessageResponse" type="tns:echoMessageResponse"/>

      </xsd:schema>
   </types>

   <message name="echoMessage">
      <part name="message" element="tns:echoMessage"/>
   </message>

   <message name="echoMessageResponse">
      <part name="result" element="tns:echoMessageResponse"/>
   </message>

   <portType name="AnyTypeMessagePortType">
      <operation name="echoMessage">
         <input message="tns:echoMessage" />
         <output message="tns:echoMessageResponse" />
      </operation>
   </portType>

   <binding name="AnyTypeMessageBinding" type="tns:AnyTypeMessagePortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="echoMessage">
         <soap:operation soapAction=""/>
         <input>
            <soap:body use="literal"/>
         </input>

         <output>
            <soap:body use="literal"/>
         </output>
      </operation>
   </binding>

   <service name="AnyTypeMessageService">
      <port binding="tns:AnyTypeMessageBinding" name="AnyTypePort">
         <soap:address location="http://localhost:8080/axis2/Services/AnyTypeMessageService"/>
      </port>

   </service>

</definitions>
