</td>
</tr>
<tr height="20px">
	<td>
	<table width="100%">
		<tr><td>
			<table width="950px">
				<tr><td><hr size="1" noshade="" /></td></tr>
				<tr>
					<td align="center">Copyright &#169; 1999-2006, The Apache Software Foundation<br />Licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>.</td>
				</tr>
			</table>
		</td>
		<td>&nbsp;</td>
		</tr>
	</table>
	</td>
</tr>
</table>
