
package org.apache.axis2.jaxws.sample.faultsservice;

import javax.xml.ws.WebFault;

import org.test.polymorphicfaults.ComplexFault;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ComplexFault", targetNamespace = "http://org/test/polymorphicfaults")
public class ComplexFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ComplexFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ComplexFault_Exception(String message, ComplexFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param message
     * @param faultInfo
     */
    public ComplexFault_Exception(String message, ComplexFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.test.polymorphicfaults.ComplexFault
     */
    public ComplexFault getFaultInfo() {
        return faultInfo;
    }

}
